### ISSUE TITLE
Chat Portraits not showing | Cannot read properties of undefined (reading 'texture')

### ISSUE THREAD

**Issue by saneronsds** [nickelpro/simply-portraits#1] opened 2022-10-19 12:30 UTC
![image](https://user-images.githubusercontent.com/17833374/196691169-04ea40ac-7748-44c7-810c-db70242015d6.png)

**Comment by nickelpro** [comment] 2022-10-19 16:41
Hmm, I'll take a look. Haven't updated foundry in a minute, what version are you running?

**Comment by saneronsds** [comment] 2022-10-19 17:03
Foundry v10 
Build 288
DnD 5e System Ver 2.0.3

**Comment by nickelpro** [comment] 2022-10-20 16:09
Updated to your version and I can't reproduce this on a fresh DnD5e world. I can fix the code such that it doesn't throw an error when `token.texture` is undefined. But when `token.texture` is undefined, I don't know where to pull the token image from in order to display a chat portrait.

**Comment by nickelpro** [comment] 2022-10-20 16:23
Oh wait, I see what happened here. The game failed to find the token listed in the message. Hmmmmmm, I hadn't thought about this. Let me think and come back to it.

Ya I can reproduce this now. Need to think about how to solve it

**Comment by nickelpro** [comment] 2022-10-20 17:20
Ok so this is fixed in 1.1, but it may be imperfect. Let me know if you continue to run into issues

**Closed as completed** 2022-10-20 17:19 UTC
